#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Futures Trading Co-Pilot — Trainer Stack Manager
# =============================================================================
#
# Manages the GPU training service defined in docker-compose.train.yml.
# The trainer is a persistent HTTP server (port 8200) that accepts training
# requests via POST /train and runs the CNN pipeline in the background.
#
# Usage:
#   ./run.train.sh                  Start the trainer server (build + up)
#   ./run.train.sh --trigger        POST /train  — kick off a training run
#   ./run.train.sh --status         Poll training status from the server
#   ./run.train.sh --sync           rsync trained models back here, restart engine
#   ./run.train.sh --down           Stop the trainer server
#   ./run.train.sh --logs           Follow trainer container logs
#   ./run.train.sh --health         Quick liveness check
#   ./run.train.sh --help           Show this message
#
# Trainer HTTP API (Tailscale IP: 100.113.72.63, port 8200):
#   GET  /health          Always 200 while server is up
#   GET  /status          Full job + model + dataset status
#   POST /train           Trigger a training run
#   POST /train/cancel    Cancel a running job
#   GET  /model           Champion model metadata
#   GET  /dataset         Dataset statistics
#   GET  /logs            Recent audit log entries
#
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

TRAINER_IP="100.113.72.63"
TRAINER_PORT="8200"
TRAINER_URL="http://${TRAINER_IP}:${TRAINER_PORT}"
COMPOSE_FILE="docker-compose.train.yml"
ENV_FILE=".env"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()     { echo -e "${CYAN}[train]${NC} $*"; }
ok()      { echo -e "${GREEN}[  ✓ ]${NC} $*"; }
warn()    { echo -e "${YELLOW}[warn]${NC} $*"; }
err()     { echo -e "${RED}[fail]${NC} $*"; }
section() { echo -e "\n${BOLD}${CYAN}── $* ──${NC}"; }

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        err "Required command not found: $1"
        exit 1
    fi
}

require_cmd docker
require_cmd curl

# Check if python3 or python is available for JSON pretty-printing
PYTHON_CMD=""
if command -v python3 >/dev/null 2>&1; then
    PYTHON_CMD="python3"
elif command -v python >/dev/null 2>&1; then
    PYTHON_CMD="python"
fi

pretty_json() {
    if [[ -n "$PYTHON_CMD" ]]; then
        "$PYTHON_CMD" -m json.tool 2>/dev/null || cat
    else
        cat
    fi
}

# ---------------------------------------------------------------------------
# .env — ensure it exists (training stack needs POSTGRES_PASSWORD etc.)
# ---------------------------------------------------------------------------

ensure_env() {
    if [[ -f "$ENV_FILE" ]]; then
        ok ".env file exists"
        return
    fi

    warn "No .env file found — generating minimal one for the trainer stack..."

    local pg_pass redis_pass
    if command -v python3 >/dev/null 2>&1; then
        pg_pass="$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")"
        redis_pass="$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")"
    else
        pg_pass="$(head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)"
        redis_pass="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 24)"
    fi

    cat > "$ENV_FILE" <<EOF
# Generated by run.train.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# These are needed to silence docker compose warnings.
# The trainer service does not use Postgres or Redis directly.
POSTGRES_PASSWORD=${pg_pass}
REDIS_PASSWORD=${redis_pass}
EOF

    ok ".env generated"
}

# ---------------------------------------------------------------------------
# Ensure bind-mount host directories exist
# ---------------------------------------------------------------------------

ensure_host_dirs() {
    local dirs=("models" "models/archive" "dataset" "data")
    for d in "${dirs[@]}"; do
        if [[ ! -d "$d" ]]; then
            mkdir -p "$d"
            log "Created host directory: $d/"
        fi
    done
}

# ---------------------------------------------------------------------------
# Wait for the trainer HTTP server to become healthy
# ---------------------------------------------------------------------------

wait_for_health() {
    local timeout_sec="${1:-120}"
    local elapsed=0
    local interval=5

    log "Waiting for trainer server at ${TRAINER_URL}/health (timeout ${timeout_sec}s)..."

    while [[ $elapsed -lt $timeout_sec ]]; do
        local http_code
        http_code=$(curl -s -o /dev/null -w "%{http_code}" \
            --connect-timeout 3 --max-time 5 \
            "${TRAINER_URL}/health" 2>/dev/null || echo "000")

        if [[ "$http_code" == "200" ]]; then
            ok "Trainer server is healthy"
            return 0
        fi

        echo -n "."
        sleep "$interval"
        elapsed=$((elapsed + interval))
    done

    echo ""
    err "Trainer server did not become healthy within ${timeout_sec}s"
    err "Check logs:  ./run.train.sh --logs"
    return 1
}

# ---------------------------------------------------------------------------
# Action: start the trainer server
# ---------------------------------------------------------------------------

cmd_start() {
    section "Starting Trainer Server"

    ensure_env
    ensure_host_dirs

    log "Building and starting trainer service..."
    docker compose -f "$COMPOSE_FILE" up --build -d

    echo ""
    wait_for_health 180

    echo ""
    ok "Trainer server is running:"
    echo "    API:     ${TRAINER_URL}"
    echo "    Health:  ${TRAINER_URL}/health"
    echo "    Status:  ${TRAINER_URL}/status"
    echo ""
    echo "  Trigger training:   ./run.train.sh --trigger"
    echo "  Watch status:       ./run.train.sh --status"
    echo "  Sync models back:   ./run.train.sh --sync"
    echo "  Follow logs:        ./run.train.sh --logs"
    echo "  Stop:               ./run.train.sh --down"
}

# ---------------------------------------------------------------------------
# Action: stop the trainer server
# ---------------------------------------------------------------------------

cmd_down() {
    section "Stopping Trainer Server"
    docker compose -f "$COMPOSE_FILE" down
    ok "Trainer server stopped"
}

# ---------------------------------------------------------------------------
# Action: health check
# ---------------------------------------------------------------------------

cmd_health() {
    local response
    response=$(curl -s --connect-timeout 5 --max-time 10 \
        "${TRAINER_URL}/health" 2>&1) || {
        err "Could not reach trainer at ${TRAINER_URL}/health"
        err "Is the trainer running?  ./run.train.sh"
        exit 1
    }

    echo "$response" | pretty_json
    local status
    status=$(echo "$response" | "$PYTHON_CMD" -c \
        "import json,sys; d=json.load(sys.stdin); print(d.get('status','unknown'))" \
        2>/dev/null || echo "unknown")
    echo ""
    ok "Trainer status: ${BOLD}${status}${NC}"
}

# ---------------------------------------------------------------------------
# Action: poll full status
# ---------------------------------------------------------------------------

cmd_status() {
    local response
    response=$(curl -s --connect-timeout 5 --max-time 10 \
        "${TRAINER_URL}/status" 2>&1) || {
        err "Could not reach trainer at ${TRAINER_URL}/status"
        err "Is the trainer running?  ./run.train.sh"
        exit 1
    }

    echo "$response" | pretty_json

    if [[ -n "$PYTHON_CMD" ]]; then
        echo ""
        "$PYTHON_CMD" - <<'PYEOF' <<< "$response" 2>/dev/null || true
import json, sys

data = json.loads(sys.stdin.read())
job  = data.get("job",     {})
mdl  = data.get("model",   {})
ds   = data.get("dataset", {})

GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
CYAN = "\033[0;36m"
BOLD = "\033[1m"
NC = "\033[0m"

print(f"{CYAN}── Summary ──{NC}")
print(f"  Job status  : {BOLD}{job.get('status','?')}{NC}")
print(f"  Message     : {job.get('message','')}")
print(f"  Run ID      : {job.get('run_id') or '(none)'}")
print(f"  Total runs  : {job.get('total_runs', 0)}")
if job.get('last_success_at'):
    print(f"  Last success: {job['last_success_at']}")
if mdl.get('champion_available'):
    sz = mdl.get('champion_size_mb','?')
    mod = mdl.get('champion_modified','?')
    print(f"  Champion    : {sz} MB  modified {mod}")
    meta = mdl.get('meta') or {}
    if meta.get('val_accuracy'):
        print(f"  Model acc   : {float(meta['val_accuracy']):.1f}%  "
              f"prec={float(meta.get('val_precision',0)):.1f}%  "
              f"recall={float(meta.get('val_recall',0)):.1f}%")
else:
    print(f"  Champion    : {YELLOW}not found — no model trained yet{NC}")
print(f"  Dataset     : {ds.get('total_samples',0)} samples  "
      f"(train={ds.get('train_samples',0)}  val={ds.get('val_samples',0)})")
PYEOF
    fi
}

# ---------------------------------------------------------------------------
# Action: trigger a training run
# ---------------------------------------------------------------------------

cmd_trigger() {
    local session="${1:-all}"
    local skip_dataset="${2:-false}"
    local dry_run="${3:-false}"
    local epochs="${4:-null}"

    section "Triggering Training Run"

    # Check current status first
    local current_status
    current_status=$(curl -s --connect-timeout 5 --max-time 10 \
        "${TRAINER_URL}/health" 2>/dev/null \
        | "$PYTHON_CMD" -c \
            "import json,sys; d=json.load(sys.stdin); print(d.get('status','unknown'))" \
            2>/dev/null || echo "unknown")

    if [[ "$current_status" == "running" ]]; then
        warn "A training job is already running!"
        warn "Check progress:  ./run.train.sh --status"
        warn "Cancel it:       curl -X POST ${TRAINER_URL}/train/cancel"
        exit 1
    fi

    log "Sending training request to ${TRAINER_URL}/train ..."
    log "  session=${session}  skip_dataset=${skip_dataset}  dry_run=${dry_run}"

    local body
    body=$(printf '{"session":"%s","skip_dataset":%s,"dry_run":%s,"immediate":true,"force":true,"epochs":%s}' \
        "$session" "$skip_dataset" "$dry_run" "$epochs")

    local response
    response=$(curl -s -X POST \
        --connect-timeout 5 --max-time 15 \
        -H 'Content-Type: application/json' \
        -d "$body" \
        "${TRAINER_URL}/train" 2>&1) || {
        err "Failed to reach trainer at ${TRAINER_URL}/train"
        exit 1
    }

    echo "$response" | pretty_json
    echo ""
    ok "Training job accepted — pipeline is running in the background"
    echo ""
    echo "  Poll status:  ./run.train.sh --status"
    echo "  Follow logs:  ./run.train.sh --logs"
    echo ""
    echo "  When complete, sync models back:"
    echo "    ./run.train.sh --sync"
}

# ---------------------------------------------------------------------------
# Action: sync models back from the trainer machine
# ---------------------------------------------------------------------------

cmd_sync() {
    section "Syncing Models from Trainer (${TRAINER_IP})"

    # Check the trainer isn't currently training (warn but don't block)
    local current_status
    current_status=$(curl -s --connect-timeout 5 --max-time 10 \
        "${TRAINER_URL}/health" 2>/dev/null \
        | "$PYTHON_CMD" -c \
            "import json,sys; d=json.load(sys.stdin); print(d.get('status','unknown'))" \
            2>/dev/null || echo "unknown")

    if [[ "$current_status" == "running" ]]; then
        warn "Training is still in progress (status=running)."
        warn "The model may be incomplete.  Sync anyway? [y/N] "
        read -r confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            log "Sync cancelled — run again when training finishes."
            exit 0
        fi
    fi

    require_cmd rsync

    bash scripts/sync_models.sh --local "${TRAINER_IP}"

    echo ""
    # Restart the engine if the main stack is running
    if docker compose ps --services 2>/dev/null | grep -q "^engine$"; then
        log "Main stack detected — restarting engine to pick up new model..."
        docker compose restart engine
        ok "Engine restarted"
    else
        warn "Main stack not running — start it with ./run.sh to use the new model"
    fi
}

# ---------------------------------------------------------------------------
# Action: follow trainer logs
# ---------------------------------------------------------------------------

cmd_logs() {
    log "Following trainer logs (Ctrl+C to stop)..."
    docker compose -f "$COMPOSE_FILE" logs -f trainer
}

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

usage() {
    cat <<EOF
Usage: ./run.train.sh [command]

Commands:
  (no args)        Build + start the trainer server, wait for healthy
  --trigger        Kick off a training run (POST /train)
  --status         Poll full training status from the server
  --health         Quick liveness check (GET /health)
  --sync           rsync trained models back here + restart engine
  --logs           Follow trainer container logs
  --down           Stop the trainer server
  --help           Show this message

Trigger options (used with --trigger):
  --session KEY    ORB session key: all (default), us, london, london_ny, both
  --skip-dataset   Skip dataset generation (train on existing data)
  --dry-run        Validate only, don't promote the model
  --epochs N       Override epoch count

Examples:
  ./run.train.sh                              # start server
  ./run.train.sh --trigger                    # train on all sessions
  ./run.train.sh --trigger --session us       # train on US session only
  ./run.train.sh --trigger --skip-dataset     # retrain on existing dataset
  ./run.train.sh --trigger --dry-run          # validate without promoting
  ./run.train.sh --trigger --epochs 10        # quick test run
  ./run.train.sh --status                     # check progress
  ./run.train.sh --sync                       # pull model + restart engine
  ./run.train.sh --down                       # stop trainer

Trainer API:  http://${TRAINER_IP}:${TRAINER_PORT}
EOF
}

# ---------------------------------------------------------------------------
# Main — parse args
# ---------------------------------------------------------------------------

ACTION="start"
TRIGGER_SESSION="all"
TRIGGER_SKIP_DATASET="false"
TRIGGER_DRY_RUN="false"
TRIGGER_EPOCHS="null"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --trigger)
            ACTION="trigger"
            shift
            ;;
        --status)
            ACTION="status"
            shift
            ;;
        --health)
            ACTION="health"
            shift
            ;;
        --sync)
            ACTION="sync"
            shift
            ;;
        --logs)
            ACTION="logs"
            shift
            ;;
        --down)
            ACTION="down"
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        # --trigger sub-options
        --session)
            TRIGGER_SESSION="$2"
            shift 2
            ;;
        --skip-dataset)
            TRIGGER_SKIP_DATASET="true"
            shift
            ;;
        --dry-run)
            TRIGGER_DRY_RUN="true"
            shift
            ;;
        --epochs)
            TRIGGER_EPOCHS="$2"
            shift 2
            ;;
        *)
            err "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

case "$ACTION" in
    start)   cmd_start ;;
    trigger) cmd_trigger "$TRIGGER_SESSION" "$TRIGGER_SKIP_DATASET" "$TRIGGER_DRY_RUN" "$TRIGGER_EPOCHS" ;;
    status)  cmd_status ;;
    health)  cmd_health ;;
    sync)    cmd_sync ;;
    logs)    cmd_logs ;;
    down)    cmd_down ;;
esac
